-- Additive only: company tables and existing records are not modified.
CREATE TABLE IF NOT EXISTS personal_ui_versions(id TEXT PRIMARY KEY,label TEXT NOT NULL,definition TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS personal_settings(user_email TEXT PRIMARY KEY,view_mode TEXT NOT NULL DEFAULT 'company' CHECK(view_mode IN ('company','personal')),reminder_mode TEXT NOT NULL DEFAULT 'company' CHECK(reminder_mode IN ('company','personal')),ui_version TEXT NOT NULL DEFAULT 'personal-v1' REFERENCES personal_ui_versions(id),updated_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS personal_ui_events(id INTEGER PRIMARY KEY,user_email TEXT NOT NULL,from_version TEXT NOT NULL,to_version TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS personal_days(user_email TEXT NOT NULL,cycle_date TEXT NOT NULL,ui_version TEXT NOT NULL REFERENCES personal_ui_versions(id),PRIMARY KEY(user_email,cycle_date));
CREATE TABLE IF NOT EXISTS personal_plans(id INTEGER PRIMARY KEY,user_email TEXT NOT NULL,cycle_date TEXT NOT NULL,ui_version TEXT NOT NULL,user_flow TEXT NOT NULL,keep TEXT NOT NULL DEFAULT '',dont_touch TEXT NOT NULL DEFAULT '',done_criteria TEXT NOT NULL DEFAULT '',unknowns TEXT NOT NULL DEFAULT '',final_prompt TEXT NOT NULL,updated_at TEXT NOT NULL DEFAULT (datetime('now')),UNIQUE(user_email,cycle_date));
CREATE TABLE IF NOT EXISTS personal_retros(id INTEGER PRIMARY KEY,user_email TEXT NOT NULL,cycle_date TEXT NOT NULL,ui_version TEXT NOT NULL,work_summary TEXT NOT NULL,ai_answer_md TEXT NOT NULL DEFAULT '',tomorrow_prompt TEXT NOT NULL DEFAULT '',updated_at TEXT NOT NULL DEFAULT (datetime('now')),UNIQUE(user_email,cycle_date));
CREATE TABLE IF NOT EXISTS personal_checks(user_email TEXT NOT NULL,cycle_date TEXT NOT NULL,ui_version TEXT NOT NULL,item_id INTEGER NOT NULL,checked INTEGER NOT NULL DEFAULT 0 CHECK(checked IN (0,1)),memo TEXT NOT NULL DEFAULT '',PRIMARY KEY(user_email,cycle_date,ui_version,item_id));
CREATE TABLE IF NOT EXISTS personal_results(id INTEGER PRIMARY KEY,user_email TEXT NOT NULL,cycle_date TEXT NOT NULL,ui_version TEXT NOT NULL,item TEXT NOT NULL,formula TEXT NOT NULL DEFAULT '',method TEXT NOT NULL DEFAULT '',result TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT '미확인' CHECK(status IN ('미확인','확인됨','불일치→수정')),category TEXT NOT NULL DEFAULT '개인 프로젝트',created_at TEXT NOT NULL DEFAULT (datetime('now')),updated_at TEXT NOT NULL DEFAULT (datetime('now')),deleted_at TEXT);
CREATE TABLE IF NOT EXISTS personal_tasks(id INTEGER PRIMARY KEY,user_email TEXT NOT NULL,task_date TEXT NOT NULL,title TEXT NOT NULL,category TEXT NOT NULL DEFAULT '개인 프로젝트',done INTEGER NOT NULL DEFAULT 0 CHECK(done IN (0,1)),created_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS personal_focus(id INTEGER PRIMARY KEY,user_email TEXT NOT NULL,focus_date TEXT NOT NULL,minutes INTEGER NOT NULL CHECK(minutes BETWEEN 1 AND 1440),note TEXT NOT NULL,category TEXT NOT NULL DEFAULT '개인 프로젝트',created_at TEXT NOT NULL DEFAULT (datetime('now')),deleted_at TEXT);
CREATE TABLE IF NOT EXISTS personal_step_marks(user_email TEXT NOT NULL,cycle_date TEXT NOT NULL,step TEXT NOT NULL CHECK(step IN ('read','share')),PRIMARY KEY(user_email,cycle_date,step));
CREATE INDEX IF NOT EXISTS personal_results_owner_date ON personal_results(user_email,cycle_date);
CREATE INDEX IF NOT EXISTS personal_tasks_owner_date ON personal_tasks(user_email,task_date);
CREATE INDEX IF NOT EXISTS personal_focus_owner_date ON personal_focus(user_email,focus_date);
INSERT INTO personal_ui_versions(id,label,definition) VALUES('personal-v1','개인용 첫 화면 · 사용자 수정 문구 반영','{"schema":1,"version":"personal-v1","title":"개인용 · 나의 준비","principles":[{"title":"오늘의 방향","description":"오늘 이룰 것과 우선순위를 정하고, 끝났는지 알 수 있는 결과를 적습니다.","target":"plan"},{"title":"직접 이해하고 판단하기","description":"모르는 내용은 예제나 비유로 생각을 확인하고, 내 말로 설명해 봅니다.","target":"check"},{"title":"결과 기록 및 오늘 하루 검토","description":"실제 결과와 작업 과정을 확인하고, 오늘 배운 점과 내일 첫 행동을 남깁니다.","target":"verif"}],"planLabels":{"user_flow":"오늘 이룰 것","keep":"이어갈 습관·자산","dont_touch":"오늘 하지 않을 일","done_criteria":"완료하면 남길 결과","unknowns":"도움 필요한 점"},"retroLabels":{"work_summary":"오늘 한 일과 배운 점","ai_answer_md":"받은 조언 / 내 생각 (선택)","tomorrow_prompt":"내일 첫 행동"},"checklist":[{"id":1,"section":"하루 방향 잡기","text":"오늘 해야 할 일, 프로젝트, 학습 중 우선순위를 골랐다"},{"id":2,"section":"하루 방향 잡기","text":"끝났는지 알 수 있는 결과 하나를 정했다"},{"id":3,"section":"하루 방향 잡기","text":"시간과 체력을 고려해 오늘 하지 않을 일을 정했다"},{"id":4,"section":"집중해서 진행하기","text":"가장 중요한 일을 작은 단계로 시작했다"},{"id":5,"section":"집중해서 진행하기","text":"모르는 내용은 예제나 비유로 생각을 확인했다"},{"id":6,"section":"집중해서 진행하기","text":"막힌 점과 다음에 확인할 것을 적었다"},{"id":7,"section":"결과 확인하기","text":"실제 결과물이나 학습 내용을 직접 확인했다"},{"id":8,"section":"결과 확인하기","text":"지원·공유할 자료의 사실과 작업 과정을 한 번 더 검토했다"},{"id":9,"section":"결과 확인하기","text":"다시 볼 수 있는 결과나 근거를 남겼다"},{"id":10,"section":"하루 마무리하기","text":"오늘 한 일과 배운 점을 기록했다"},{"id":11,"section":"하루 마무리하기","text":"내일 먼저 할 행동 하나를 정했다"},{"id":12,"section":"하루 마무리하기","text":"무리하지 않도록 휴식과 다음 일정을 확인했다"}]}') ON CONFLICT(id) DO NOTHING;
