"use strict";
const SERVICE="work-cycle";
const KEY="portfolio-demo:"+SERVICE+":v1";
const seed=()=>({read:[],tasks:{t1:"할 일",t2:"진행 중",t3:"완료"},done:[],notes:"",retro:""});
let state;try{state=JSON.parse(localStorage.getItem(KEY))||seed()}catch{state=seed()}
const raw=state&&typeof state==='object'?state:{};
state=seed();
for(const k of ['read','done'])if(Array.isArray(raw[k]))state[k]=raw[k].filter(v=>typeof v==='string');
for(const k of ['notes','retro'])if(typeof raw[k]==='string')state[k]=raw[k];
for(const id of Object.keys(state.tasks))if(raw.tasks&&['할 일','진행 중','완료'].includes(raw.tasks[id]))state.tasks[id]=raw.tasks[id];let page="home",meeting=null,tab="summary",query="",filter="all";
const meetings=[{id:"m1",date:"2026-10-02",title:"모바일 대시보드 개선 회의",summary:"작은 화면에서 중요한 기록과 다음 행동을 먼저 보여주기로 했습니다.",original:"가상 회의 원문: 목록에서 제목을 충분히 읽을 수 있게 하고, 요약과 원문을 분리합시다. 다음 주에는 화면 검토를 진행합니다.",actions:["회의록 카드 화면 검토","검색과 읽음 상태 확인"]},{id:"m2",date:"2026-10-01",title:"주간 일정 조정 회의",summary:"이번 주 우선순위를 정하고 작업 시간을 나누었습니다.",original:"가상 회의 원문: 오전에는 핵심 작업을, 오후에는 결과 확인과 기록 정리를 진행합니다.",actions:["핵심 일정 2개 정리"]}];
const titles={home:"오늘",meetings:"회의록",schedule:"일정",kanban:"칸반",projects:"프로젝트",development:"개발 이력",notes:"노트",study:"공부",retro:"회고",report:"주간보고",readiness:"준비 현황",more:"더보기"};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const card=(title,body)=>`<section class="card"><h2>${title}</h2>${body}</section>`;
const go=(id,label)=>`<button data-page="${id}">${label||titles[id]}</button>`;
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{announce("저장 공간을 사용할 수 없어 이번 화면에서만 체험합니다.")}}
function announce(s){document.querySelector('#notice').textContent=s}
function render(){document.querySelector('#title').textContent=titles[page];document.querySelectorAll('nav button').forEach(b=>{b.removeAttribute('aria-current');if(b.dataset.page===(['home','projects','meetings'].includes(page)?page:'more'))b.setAttribute('aria-current','page')});let html="";
if(page==='home')html=card('오늘의 중요한 일',`<p>가상 일정 · 오전 9시 화면 검토</p><p>다음 행동: 회의에서 정한 작업을 확인하세요.</p><div class="row">${go('meetings','회의록 확인')}${go('kanban','작업 진행')}</div>`)+card(SERVICE==='work-cycle'?'업무 진행':'개인 생활 정리',`<p>${SERVICE==='work-cycle'?'요구사항 확인 → 작업 → 결과 검토':'정리할 일 3개를 골라 작은 작업부터 시작합니다.'}</p>${go('schedule')}`);
if(page==='meetings'){if(meeting){let m=meetings.find(x=>x.id===meeting);html=`<button id="back">목록으로</button>`+card(esc(m.title),`<small>${m.date} · 허구 예시</small><div class="tabs">${[['summary','요약'],['original','원문'],['actions','할 일'],['history','이력']].map(([id,label])=>`<button data-tab="${id}" aria-pressed="${tab===id}">${label}</button>`).join('')}</div>${tab==='summary'?`<p>${esc(m.summary)}</p>`:tab==='original'?`<p>${esc(m.original)}</p>`:tab==='history'?`<p>${m.date} · 예시 문서 생성</p><p>원본 연결: 공개 데모에서는 제공하지 않습니다.</p>`:m.actions.map((a,i)=>`<label><input type="checkbox" data-done="${m.id}-${i}" ${state.done.includes(m.id+'-'+i)?'checked':''}> ${esc(a)}</label>`).join('')}<button id="read" class="primary">${state.read.includes(m.id)?'읽음 취소':'읽음 표시'}</button>`)}else{html=`<label>제목 검색<input type="search" id="search" value="${esc(query)}"></label><label>읽음 상태 <select id="filter"><option value="all">전체</option><option value="unread" ${filter==='unread'?'selected':''}>읽지 않음</option><option value="read" ${filter==='read'?'selected':''}>읽음</option></select></label><div id="meeting-list"></div>`}}
if(page==='schedule')html=card('날짜별 일정','<h3>10월 5일 월요일</h3><p>09:00 · 모바일 화면 검토</p><p>14:00 · 예시 데이터 확인</p>')+card('10월 6일 화요일','<p>10:00 · 개선 결과 기록</p>');
if(page==='kanban')html=Object.entries(state.tasks).map(([id,status],i)=>card(['회의록 화면 검토','일정 확인','예시 데이터 준비'][i],`<label>상태 <select data-task="${id}">${['할 일','진행 중','완료'].map(s=>`<option ${s===status?'selected':''}>${s}</option>`).join('')}</select></label>`)).join('');
if(page==='projects')html=card('모바일 기록 도구','<span class="badge">진행 중</span><p>다음 행동: 회의록 상세 화면 점검</p>'+go('development'))+card('센서 화면 예시','<span class="badge">검토 중</span><p>허구 프로젝트입니다. 실제 설비 정보가 없습니다.</p>');
if(page==='development')html=card('2026-10-02 · 회의록 카드 개선','<p>무엇을: 제목과 날짜를 분리했습니다.</p><p>왜: 작은 화면에서 제목을 읽기 쉽게 하기 위해서입니다.</p><p>어떻게: 목록을 세로 카드로 구성했습니다.</p>');
if(page==='notes'||page==='retro')html=card(page==='notes'?'나의 예시 노트':'오늘의 회고',`<label>${page==='notes'?'메모':'잘한 일과 다음 행동'}<textarea id="text">${esc(state[page])}</textarea></label><button id="save-text" class="primary">이 브라우저에 저장</button><p>체험 초기화를 누르면 삭제됩니다.</p>`);
if(page==='study')html=card('이번 주 공부','<p>주제: 작은 화면에서 사용하기 쉬운 인터페이스</p><label><input type="checkbox" data-done="study" '+(state.done.includes('study')?'checked':'')+'> 예시 학습 완료</label>');
if(page==='report')html=card('예시 주간보고','<p>이번 주: 회의록 카드 개선과 일정 정리</p><details><summary>월요일</summary><p>요구사항을 확인했습니다.</p></details><details><summary>화요일</summary><p>화면을 검토했습니다.</p></details>');
if(page==='readiness')html=card('준비 현황','<p>다음 행동: 화면 확인 항목 점검</p><label><input type="checkbox" data-done="ready" '+(state.done.includes('ready')?'checked':'')+'> 모바일 화면 확인</label>');
if(page==='more')html=card('화면 선택',`<div class="row">${['schedule','kanban','readiness','report','development','notes','study','retro'].map(id=>go(id)).join('')}</div>`)+card('체험 안내','<p>작업 상태와 노트는 이 브라우저에만 저장됩니다. 실제 계정·회의록·달력·알림에는 연결되지 않습니다.</p>');
document.querySelector('#content').innerHTML=html;if(page==='meetings'&&!meeting)renderList();}
function renderList(){let rows=meetings.filter(m=>m.title.includes(query)&&(filter==='all'||state.read.includes(m.id)===(filter==='read')));document.querySelector('#meeting-list').innerHTML=rows.length?rows.map(m=>card(esc(m.title),`<small>${m.date} · ${state.read.includes(m.id)?'읽음':'읽지 않음'}</small><p>${esc(m.summary)}</p><button data-meeting="${m.id}" class="primary">상세 보기</button>`)).join(''):'<p>일치하는 회의록이 없습니다.</p>'}
document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.page){page=b.dataset.page;meeting=null;render();document.querySelector('#content').focus();window.scrollTo(0,0)}if(b.dataset.meeting){meeting=b.dataset.meeting;tab='summary';render();document.querySelector('#content').focus();window.scrollTo(0,0)}if(b.dataset.tab){tab=b.dataset.tab;render();document.querySelector('[data-tab='+tab+']').focus()}if(b.id==='back'){const prior=meeting;meeting=null;render();document.querySelector('[data-meeting='+prior+']')?.focus()}if(b.id==='read'){state.read=state.read.includes(meeting)?state.read.filter(id=>id!==meeting):[...state.read,meeting];save();render();document.querySelector('#read').focus();announce('읽음 상태가 변경되었습니다.')}if(b.id==='save-text'){state[page]=document.querySelector('#text').value;save();announce('체험 내용을 이 브라우저에 저장했습니다.')}if(b.id==='reset'){state=seed();try{localStorage.removeItem(KEY)}catch{}page='home';meeting=null;query='';filter='all';render();announce('체험 데이터를 초기화했습니다.')}});
document.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value;renderList()}});
document.addEventListener('change',e=>{let t=e.target;if(t.id==='filter'){filter=t.value;renderList()}if(t.dataset.task){state.tasks[t.dataset.task]=t.value;save();announce('작업 상태를 변경했습니다.')}if(t.dataset.done){state.done=t.checked?[...state.done,t.dataset.done]:state.done.filter(id=>id!==t.dataset.done);save();announce('확인 상태를 변경했습니다.')}});render();
